default:
  image: shared-docker-remote.artifactory.int.bell.ca/node:20
  tags:
    - shared-runner
    - shared-runner-aws
    - shared-runner-docker
    - shared-runner-CI
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

stages:
  - package
  - test
  - install-node-modules
  - check-code-build
  - deploy
  - deploy-artifact


npm-build:
  stage: package
  artifacts:
    paths:
      - node_modules
      - dist
  script:
    - npm ci
    - npm install @rspack/binding-linux-x64-gnu
    - npm run build
  before_script:
    - ls -la
    - if [ -d "node_modules" ]; then echo "node_modules exists"; else echo "node_modules does not exist"; fi
    - echo $PRODUCTION_ENV_FILE > .env.production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

npm-test:
  stage: test
  script:
    # - npx playwright install --with-deps
    - npm run test:component
    - npm run test:unit
    # - npx playwright test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

include:
  project: 'cornerstone-factory/tonic-platform/ci-templates'  
  file: 
    - storybook/storybook.base.yml   

node-modules-install-job:
  rules:
    - when: never

check-code-build-job:
  rules:
    - when: never

pages:
  rules:
    - when: never

deploy-artifact-job:
  rules:
    - when: never

deploy-codeartifact-job:
  before_script:
    - echo $CI_SERVER_HOST
    - echo $EXPLAT_REGISTRY
    - apt-get update -y && apt install awscli jq -y
    - ROLE=$(aws sts assume-role --role-arn "arn:aws:iam::${DOMAIN_OWNER}:role/${AWS_IAM_ROLE}" --role-session-name AWSCLI-Session)
    - export AWS_ACCESS_KEY_ID=$(echo $ROLE | jq -r '.Credentials.AccessKeyId')
    - export AWS_SECRET_ACCESS_KEY=$(echo $ROLE | jq -r '.Credentials.SecretAccessKey')
    - export AWS_SESSION_TOKEN=$(echo $ROLE | jq -r '.Credentials.SessionToken')
    - aws sts get-caller-identity
    - echo "@buycomponent:registry=${EXPLAT_REGISTRY}" > .npmrc
    - git config --global user.email "buycomponent@bell.ca"
    - git config --global user.name "buycomponentadmin"
    - npm version patch
    - aws codeartifact login --tool npm --repository npm --domain tonic --domain-owner ${DOMAIN_OWNER} --region us-east-1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
    - when: never

