default:
  image: shared-docker-remote.artifactory.int.bell.ca/node:20
  tags:
    - shared-runner
    - shared-runner-aws
    - shared-runner-docker
    - shared-runner-CI
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

stages:
  - package
  - test

npm-build:
  stage: package
  artifacts:
    paths:
      - node_modules
      - dist
  script:
    - npm ci
    - npm install @rspack/binding-linux-x64-gnu
    - npm run build
  before_script:
    - ls -la
    - if [ -d "node_modules" ]; then echo "node_modules exists"; else echo "node_modules does not exist"; fi
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

npm-test:
  stage: test
  script:
    - npx playwright install --with-deps
    - npm run test:component
    - npx playwright test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"