export const CT_CLIENT_CREDENTIALS : any = {
  CLIENT_ID: process.env.PUBLIC_CT_CLIENT_ID,
  CLIENT_SECRET: process.env.PUBLIC_CT_CLIENT_SECRET,
  PROJECT_KEY: process.env.PUBLIC_CT_PROJECT_KEY,
  }

export const CT_BASE_URLS : any = {
    CT_HOST: process.env.PUBLIC_CT_HOST,
    AUTH_URL: process.env.PUBLIC_AUTH_URL,
  }

export const CONTENTSTACK_CREDENTIALS: any = {
    API_KEY: process.env.PUBLIC_CONTENTSTACK_API_KEY,
    DELIVERY_TOKEN: process.env.PUBLIC_CONTENTSTACK_DELIVERY_TOKEN,
    ENVIRONMENT: process.env.PUBLIC_CONTENTSTACK_ENVIRONMENT,
  };


